# Generates .env.production with strong random secrets already filled in.
# Equivalent to init-env.sh, for hosts without a POSIX shell.
#
# Only two values cannot be guessed — the public addresses of the admin site
# and the API — so the script asks for those and derives everything else. In
# particular it assembles DATABASE_URL from the generated password, which is
# the value most often left pointing at the old credentials when secrets are
# edited by hand.
#
#   .\scripts\init-env.ps1
#   .\scripts\init-env.ps1 -AdminUrl https://vacuum-admin.example.com -ApiUrl https://vacuum-api.example.com

param(
  [string]$AdminUrl = '',
  [string]$ApiUrl = '',
  [string]$Output = '.env.production',
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

if ((Test-Path -LiteralPath $Output) -and (-not $Force)) {
  Write-Host "Refusing to overwrite the existing $Output." -ForegroundColor Yellow
  Write-Host 'Its secrets are already in use by the running database and storage.'
  Write-Host 'Pass -Force only if you are certain, and read the credential-change'
  Write-Host 'section of docs/PRODUCTION_DEPLOYMENT.md first.'
  exit 1
}

# Alphanumeric only: these values are embedded in a URL and passed through a
# shell, and punctuation would need escaping in both.
function New-Secret {
  param([int]$Length)

  $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
  $bytes = [byte[]]::new($Length * 2)
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }

  $chars = foreach ($b in $bytes) { $alphabet[$b % $alphabet.Length] }
  -join ($chars | Select-Object -First $Length)
}

function Normalize-Url {
  param([string]$Value)
  $trimmed = $Value.Trim()
  if ($trimmed.EndsWith('/')) { $trimmed = $trimmed.TrimEnd('/') }
  return $trimmed
}

if (-not $AdminUrl) {
  $AdminUrl = Read-Host 'Public address of the admin site (e.g. https://vacuum-admin.example.com)'
}

if (-not $ApiUrl) {
  $ApiUrl = Read-Host 'Public address of the API (e.g. https://vacuum-api.example.com)'
}

$AdminUrl = Normalize-Url $AdminUrl
$ApiUrl = Normalize-Url $ApiUrl

foreach ($url in @($AdminUrl, $ApiUrl)) {
  if (-not ($url -match '^https?://')) {
    throw "Addresses must start with http:// or https:// - got: $url"
  }
}

if ($AdminUrl -match '^http://') {
  Write-Host 'Warning: the admin address is not HTTPS. Sign-in credentials would travel unencrypted.' -ForegroundColor Yellow
}

$postgresDb = 'vacuum_traceability'
$postgresUser = 'vacuum_user'
$postgresPassword = New-Secret -Length 32
$minioUser = 'vacuum_storage_' + (New-Secret -Length 8)
$minioPassword = New-Secret -Length 40
$jwtSecret = New-Secret -Length 64
$today = Get-Date -Format 'yyyy-MM-dd'

$content = @"
# Generated by scripts/init-env.ps1 on $today.
# Contains live production secrets. Never commit this file.
#
# Before changing POSTGRES_USER or POSTGRES_PASSWORD on a system that already
# holds data, read the credential-change section of
# docs/PRODUCTION_DEPLOYMENT.md: PostgreSQL applies them only when it first
# creates the database, so editing them here later has no effect.

COMPOSE_PROJECT_NAME=vacuum-traceability-prod

# PostgreSQL. DATABASE_URL repeats the user and password above; the three must
# always be changed together.
POSTGRES_DB=$postgresDb
POSTGRES_USER=$postgresUser
POSTGRES_PASSWORD=$postgresPassword
DATABASE_URL=postgresql://${postgresUser}:${postgresPassword}@postgres:5432/${postgresDb}?schema=public

# MinIO object storage. The bucket stays private and is never published; the
# backend serves photos itself. S3_ACCESS_KEY/S3_SECRET_KEY are the credentials
# the backend signs in with, so they match the root user above.
MINIO_ROOT_USER=$minioUser
MINIO_ROOT_PASSWORD=$minioPassword
S3_ENDPOINT=http://minio:9000
S3_BUCKET=vacuum-photos
S3_ACCESS_KEY=$minioUser
S3_SECRET_KEY=$minioPassword
S3_USE_SSL=false
# Ignored by MinIO. Set it only when pointing at real AWS S3.
S3_REGION=us-east-1

# Backend
NODE_ENV=production
PORT=3000
APP_NAME=vacuum-traceability-api
CORS_ORIGIN=$AdminUrl,$ApiUrl
BACKEND_PUBLIC_URL=$ApiUrl
ADMIN_PUBLIC_URL=$AdminUrl
FIREBASE_SERVICE_ACCOUNT_PATH=

# Signs the tokens issued at sign-in. Changing it signs everyone out.
JWT_SECRET=$jwtSecret
JWT_EXPIRES_IN_SECONDS=43200

# Loopback ports for the reverse proxy that terminates TLS. PostgreSQL and
# MinIO are deliberately not published at all.
BACKEND_HTTP_PORT=3000
ADMIN_HTTP_PORT=8080

# Image names and tag.
BACKEND_IMAGE=vacuum-traceability-backend
BACKEND_MIGRATION_IMAGE=vacuum-traceability-backend-migration
ADMIN_IMAGE=vacuum-traceability-admin
IMAGE_TAG=local
"@

# UTF8 without BOM: Docker Compose does not strip a byte-order mark, and would
# read it as part of the first variable name.
$outputPath = if ([System.IO.Path]::IsPathRooted($Output)) {
  $Output
} else {
  Join-Path (Get-Location).Path $Output
}

[System.IO.File]::WriteAllText(
  $outputPath,
  $content,
  (New-Object System.Text.UTF8Encoding $false)
)

Write-Host ''
Write-Host "Wrote $Output with generated secrets." -ForegroundColor Green
Write-Host ''
Write-Host 'Next:'
Write-Host "  1. docker compose -f docker-compose.prod.yml --env-file $Output up -d --build"
Write-Host '  2. Create the first administrator - see docs/USER_MANAGEMENT.md section 3.'
Write-Host '  3. Point your reverse proxy at 127.0.0.1:3000 (API) and 127.0.0.1:8080 (admin).'
Write-Host ''
Write-Host 'Back this file up somewhere safe. Losing JWT_SECRET signs everyone out;'
Write-Host 'losing the database password locks the application out of its own data.'
