#!/usr/bin/env bash
# Generates .env.production with strong random secrets already filled in.
#
# Only two values cannot be guessed — the public addresses of the admin site
# and the API — so the script asks for those and derives everything else. In
# particular it assembles DATABASE_URL from the generated password, which is
# the value most often left pointing at the old credentials when secrets are
# edited by hand.
#
# Usage:
#   ./scripts/init-env.sh
#   ./scripts/init-env.sh --admin-url https://vacuum-admin.example.com --api-url https://vacuum-api.example.com
#   ./scripts/init-env.sh --output .env.production --force

set -euo pipefail

ADMIN_URL=""
API_URL=""
OUTPUT=".env.production"
FORCE="no"

while [ $# -gt 0 ]; do
  case "$1" in
    --admin-url) ADMIN_URL="$2"; shift 2 ;;
    --api-url)   API_URL="$2";   shift 2 ;;
    --output)    OUTPUT="$2";    shift 2 ;;
    --force)     FORCE="yes";    shift ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *)
      echo "Unknown option: $1" >&2
      echo "Run with --help for usage." >&2
      exit 1 ;;
  esac
done

if [ -f "$OUTPUT" ] && [ "$FORCE" != "yes" ]; then
  echo "Refusing to overwrite the existing $OUTPUT." >&2
  echo "Its secrets are already in use by the running database and storage." >&2
  echo "Pass --force only if you are certain, and read the credential-change" >&2
  echo "section of docs/PRODUCTION_DEPLOYMENT.md first." >&2
  exit 1
fi

# Alphanumeric only: these values are embedded in a URL and passed through a
# shell, and punctuation would need escaping in both.
random_secret() {
  local length="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 $((length * 2)) | tr -dc 'A-Za-z0-9' | head -c "$length"
  elif [ -r /dev/urandom ]; then
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$length"
  elif command -v node >/dev/null 2>&1; then
    node -e "process.stdout.write(require('crypto').randomBytes($length * 2).toString('base64').replace(/[^A-Za-z0-9]/g,'').slice(0,$length))"
  else
    echo "No source of randomness found (need openssl, /dev/urandom or node)." >&2
    exit 1
  fi
}

normalize_url() {
  # Strip a trailing slash so joined paths never contain a double slash.
  printf '%s' "${1%/}"
}

if [ -z "$ADMIN_URL" ]; then
  printf 'Public address of the admin site (e.g. https://vacuum-admin.example.com): '
  read -r ADMIN_URL
fi

if [ -z "$API_URL" ]; then
  printf 'Public address of the API (e.g. https://vacuum-api.example.com): '
  read -r API_URL
fi

ADMIN_URL="$(normalize_url "$ADMIN_URL")"
API_URL="$(normalize_url "$API_URL")"

for url in "$ADMIN_URL" "$API_URL"; do
  case "$url" in
    http://*|https://*) ;;
    *)
      echo "Addresses must start with http:// or https:// — got: $url" >&2
      exit 1 ;;
  esac
done

case "$ADMIN_URL" in
  http://*) echo "Warning: the admin address is not HTTPS. Sign-in credentials would travel unencrypted." >&2 ;;
esac

POSTGRES_DB="vacuum_traceability"
POSTGRES_USER="vacuum_user"
POSTGRES_PASSWORD="$(random_secret 32)"
MINIO_USER="vacuum_storage_$(random_secret 8)"
MINIO_PASSWORD="$(random_secret 40)"
JWT_SECRET="$(random_secret 64)"

umask 077
cat > "$OUTPUT" <<EOF
# Generated by scripts/init-env.sh on $(date +%Y-%m-%d).
# Contains live production secrets. Never commit this file.
#
# Before changing POSTGRES_USER or POSTGRES_PASSWORD on a system that already
# holds data, read the credential-change section of
# docs/PRODUCTION_DEPLOYMENT.md: PostgreSQL applies them only when it first
# creates the database, so editing them here later has no effect.

COMPOSE_PROJECT_NAME=vacuum-traceability-prod

# PostgreSQL. DATABASE_URL repeats the user and password above; the three must
# always be changed together.
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?schema=public

# MinIO object storage. The bucket stays private and is never published; the
# backend serves photos itself. S3_ACCESS_KEY/S3_SECRET_KEY are the credentials
# the backend signs in with, so they match the root user above.
MINIO_ROOT_USER=$MINIO_USER
MINIO_ROOT_PASSWORD=$MINIO_PASSWORD
S3_ENDPOINT=http://minio:9000
S3_BUCKET=vacuum-photos
S3_ACCESS_KEY=$MINIO_USER
S3_SECRET_KEY=$MINIO_PASSWORD
S3_USE_SSL=false
# Ignored by MinIO. Set it only when pointing at real AWS S3.
S3_REGION=us-east-1

# Backend
NODE_ENV=production
PORT=3000
APP_NAME=vacuum-traceability-api
CORS_ORIGIN=$ADMIN_URL,$API_URL
BACKEND_PUBLIC_URL=$API_URL
ADMIN_PUBLIC_URL=$ADMIN_URL
FIREBASE_SERVICE_ACCOUNT_PATH=

# Signs the tokens issued at sign-in. Changing it signs everyone out.
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN_SECONDS=43200

# Loopback ports for the reverse proxy that terminates TLS. PostgreSQL and
# MinIO are deliberately not published at all.
BACKEND_HTTP_PORT=3000
ADMIN_HTTP_PORT=8080

# Image names and tag.
BACKEND_IMAGE=vacuum-traceability-backend
BACKEND_MIGRATION_IMAGE=vacuum-traceability-backend-migration
ADMIN_IMAGE=vacuum-traceability-admin
IMAGE_TAG=local
EOF

chmod 600 "$OUTPUT" 2>/dev/null || true

echo
echo "Wrote $OUTPUT with generated secrets."
echo
echo "Next:"
echo "  1. docker compose -f docker-compose.prod.yml --env-file $OUTPUT up -d --build"
echo "  2. Create the first administrator — see docs/USER_MANAGEMENT.md section 3."
echo "  3. Point your reverse proxy at 127.0.0.1:3000 (API) and 127.0.0.1:8080 (admin)."
echo
echo "Back this file up somewhere safe. Losing JWT_SECRET signs everyone out;"
echo "losing the database password locks the application out of its own data."
